liip_imagine:
    driver: 'gd'
    loaders:
        default:
            filesystem:
                locator: 'filesystem_insecure'
    resolvers:
        default:
            web_path: ~
    twig:
        mode: 'lazy'
        assets_version: '%admin_tag_version%'
    webp:
        generate: true
    default_filter_set_settings:
        format: 'webp'
    filter_sets:
        cache: ~
        3500xY:
            quality: 75
            filters:
                thumbnail: { size: [ 3500, null ], mode: 'outbound' }
        2400xY:
            quality: 75
            filters:
                thumbnail: { size: [ 2400, null ], mode: 'outbound' }
        1200xY:
            quality: 75
            filters:
                thumbnail: { size: [ 1200, null ], mode: 'outbound' }
        960xY:
            quality: 100
            filters:
                thumbnail: { size: [ 960, null ], mode: 'outbound' }
        585xY:
            quality: 100
            filters:
                thumbnail: { size: [ 585, null ], mode: 'outbound' }
        500xY:
            quality: 100
            filters:
                thumbnail: { size: [ 500, null ], mode: 'outbound' }
        480xY:
            quality: 100
            filters:
                thumbnail: { size: [ 480, null ], mode: 'outbound' }
        480x620:
            quality: 100
            filters:
                thumbnail: { size: [ 480, 620 ], mode: 'outbound' }
        231x50:
            quality: 80
            filters:
                thumbnail: { size: [ 231, 50 ], mode: 'outbound' }
        200xY:
            quality: 90
            filters:
                thumbnail: { size: [ 200, null ], mode: 'outbound' }
        200xY_BW:
            quality: 90
            filters:
                thumbnail: { size: [ 200, null ], mode: 'outbound' }
                grayscale: ~
        150xY:
            quality: 90
            filters:
                thumbnail: { size: [ 150, null ], mode: 'outbound' }
        150xY_BW:
            quality: 90
            filters:
                thumbnail: { size: [ 150, null ], mode: 'outbound' }
                grayscale: ~
        140x140:
            quality: 90
            filters:
                thumbnail: { size: [ 140, 140 ], mode: 'outbound' }
        132x50:
            quality: 85
            filters:
                thumbnail: { size: [ 132, 50 ], mode: 'outbound' }
        100xY:
            quality: 95
            filters:
                thumbnail: { size: [ 100, null ], mode: 'outbound' }
        60x60:
            quality: 95
            filters:
                thumbnail: { size: [ 60, 60 ], mode: 'outbound' }
