framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            urgent: [ 'email' ]
            high: [ 'email' ]
            medium: [ 'email' ]
            low: [ 'email' ]
        admin_recipients:
            - { email: '%customer_delivery_address%' }
