security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    role_hierarchy:
        ROLE_SONATA_CMS:
            - 'ROLE_ADMIN_CATEGORY_ALL'
            - 'ROLE_ADMIN_PROJECT_ALL'
            - 'ROLE_ADMIN_PROJECT_IMAGE_ALL'
            - 'ROLE_ADMIN_WORKSHOP_ALL'
            - 'ROLE_ADMIN_WORKSHOP_IMAGE_ALL'
        ROLE_ADMIN:
            - 'ROLE_USER'
            - 'ROLE_SONATA_ADMIN'
            - 'ROLE_SONATA_CMS'
        ROLE_SUPER_ADMIN:
            - 'ROLE_ADMIN'
            - 'ROLE_ADMIN_USER_ALL'
            - 'ROLE_ALLOWED_TO_SWITCH'
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '%admin_password%', roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        admin:
            lazy: true
            pattern: '/admin(.*)'
            provider: 'backend_users'
            entry_point: 'form_login'
            context: 'admin'
            form_login:
                login_path: 'login'
                check_path: 'login'
                failure_path: 'login'
                username_parameter: 'username'
                password_parameter: 'password'
                enable_csrf: true
            logout:
                path: 'logout'
                target: 'login'
    access_control:
        - { path: ^/admin/login$, role: 'PUBLIC_ACCESS' }
        - { path: ^/admin/logout$, role: 'PUBLIC_ACCESS' }
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
        - { path: ^/.*, role: 'PUBLIC_ACCESS' }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: 'auto'
                cost: 4
                time_cost: 3
                memory_cost: 10
