sonata_admin:
    title: 'Sonata Admin'
    persist_filters: true
    show_mosaic_button: false
    search: false
    options:
        html5_validate: true
        confirm_exit: true
        use_select2: true
        use_icheck: true
        use_stickyforms: true
        use_bootlint: false
        js_debug: false
        default_admin_route: 'edit'
        default_translation_domain: 'messages'
        default_icon: 'fas fa-folder'
        logo_content: 'icon'                # text | icon | all
        list_action_button_content: 'icon'  # text | icon | all
    security:
        handler: 'sonata.admin.security.handler.role'
        role_admin: 'ROLE_ADMIN'
        role_super_admin: 'ROLE_SUPER_ADMIN'
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        groups:
            Content:
                keep_open: true
        blocks:
            - { type: 'sonata.admin.block.admin_list', position: 'left' }

when@dev:
    sonata_admin:
        options:
            use_bootlint: true
            js_debug: true
