stof_doctrine_extensions:
    default_locale: '%default_locale%'
    persist_default_translation: false
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            softdeleteable: false
            sortable: false
            tree: false
