twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': 'App'
        '%kernel.project_dir%/assets/styles': 'styles'
        '%kernel.project_dir%/assets/images': 'images'
    form_themes:
        - 'form_themes/vich_uploader_fields.html.twig'
    globals:
        project_title: 'Miguel Bustos CMS'
        admin_tag_version: '%admin_tag_version%'

when@test:
    twig:
        strict_variables: true
