parameters:
    default_locale: 'es'
    admin_tag_version: '100000'
    admin_password: '%env(string:ADMIN_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Sonata Admins
    admin.category:
        class: 'App\Admin\CategoryAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Category', controller: ~, manager_type: 'orm', group: 'Contenido', label: 'Categorías' }
    admin.project:
        class: 'App\Admin\ProjectAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Project', controller: ~, manager_type: 'orm', group: 'Contenido', label: 'Proyectos' }
    admin.project_image:
        class: 'App\Admin\Image\ProjectImageAdmin'
        tags:
            - { name: 'sonata.admin', model_class: 'App\Entity\Image\ProjectImage', controller: ~, manager_type: 'orm', group: 'Contenido', label: 'Imagenes', show_in_dashboard: false }
