imports:
    - { resource: 'admins.yaml' }

parameters:
    default_locale: 'es'
    locale_i18n: [ 'en', 'ca' ]
    locale_i18n_full: [ 'es', 'en', 'ca' ]
    short_project_title: 'MB CMS'
    project_title: 'Miguel Bustos'
    customer_mobile_phone: '%env(string:CUSTOMER_MOBILE_PHONE)%'
    admin_tag_version: '100006'
    admin_password: '%env(string:ADMIN_PASSWORD)%'
    delivery_dev_address: '%env(string:DEV_DELIVERY_ADDRESS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          '$locales': '%locale_i18n_full%'
    App\:
        resource: '../src/'
    # Events
    App\Form\EventListener\DefaultTranslationsListener:
        arguments:
            - '@App\Form\Translation\GedmoTranslationForm'
    App\Form\EventListener\GedmoTranslationsListener:
        arguments:
            - '@App\Form\Translation\GedmoTranslationForm'
    App\Form\Translation\DefaultTranslationForm:
        arguments:
            - '@form.registry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
    App\Form\Translation\GedmoTranslationForm:
        arguments:
            - '@form.registry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
        calls:
            - setGedmoTranslatableListener: [ '@stof_doctrine_extensions.listener.translatable' ]
    # Forms
    App\Form\Type\GedmoTranslationsType:
        arguments:
            - '@App\Form\EventListener\GedmoTranslationsListener'
            - '@App\Form\Translation\GedmoTranslationForm'
            - '%locale_i18n%'
            - ~
        tags:
            - { name: 'form.type' }
    App\Form\Type\TranslationsFormsType:
        arguments:
            - '%locale_i18n%'
            - ~
        tags:
            - { name: 'form.type' }
